name: flame_ldtk_example
description: Example app for flame_ldtk package
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  flame_ldtk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_test: ^2.0.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/world-simplified/simplified/Level_0/
    - assets/world-simplified/
    - assets/world-simplified.ldtk
    - assets/tilemap_packed.png
    - assets/colored_forest.png
