codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

# Combine coverage from unit tests and integration tests
flag_management:
  default_rules:
    carryforward: true

flags:
  unittests:
    paths:
      - lib/
    carryforward: true
  integration:
    paths:
      - lib/
    carryforward: true

# Ignore generated files and test files from coverage
ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.mocks.dart"
  - "test/**"
  - "example/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
