name: flame_ldtk
description: A Flutter package for integrating LDtk levels into Flame Engine games
version: 0.1.0
homepage: https://github.com/thomascarvalho/flame_ldtk
repository: https://github.com/thomascarvalho/flame_ldtk
issue_tracker: https://github.com/thomascarvalho/flame_ldtk/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  flutter_lints: ^4.0.0
