name: flame_ldtk
description: LDtk support for flame-engine. Integrate LDtk levels into Flame Engine games.
version: 0.3.0
homepage: https://github.com/thomascarvalho/flame_ldtk
repository: https://github.com/thomascarvalho/flame_ldtk
issue_tracker: https://github.com/thomascarvalho/flame_ldtk/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_test: ^2.0.3
  test: ^1.26.0
  flutter_lints: ^6.0.0
