name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.x'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Check pub.dev score (dry-run)
        run: dart pub publish --dry-run

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.x'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage --reporter expanded

      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-unittests
          fail_ci_if_error: false

      - name: Get example dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Run integration tests (example)
        working-directory: ./example
        run: flutter test --coverage --reporter expanded

      - name: Upload integration test coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./example/coverage/lcov.info
          flags: integration
          name: codecov-integration
          fail_ci_if_error: false

      
